BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Exams" (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL UNIQUE,
	"grade"	INTEGER NOT NULL,
	"date"	INTEGER NOT NULL,
	"description"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Features" (
	"id"	INTEGER NOT NULL UNIQUE,
	"id_exam"	INTEGER NOT NULL,
	"name"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("id_exam") REFERENCES "Exams"("id")
);
CREATE TABLE IF NOT EXISTS "Projects" (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL UNIQUE,
	"date"	INTEGER NOT NULL,
	"image"	TEXT NOT NULL,
	"description"	TEXT NOT NULL,
	"link"	TEXT,
	"extra"	TEXT,
	"status"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Tools" (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL,
	"id_project"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("id_project") REFERENCES "Projects"("id")
);
INSERT INTO "Exams" ("id","name","grade","date","description") VALUES (4,'Data Science e Tecnologie per le Basi di Dati',31,'2025-01-20','Studio delle tecnologie per la gestione di basi di dati relazionali e non relazionali (NoSQL), incluse le architetture distribuite e le tecniche di replica. Progettazione fisica di database, modellazione e sviluppo di data warehouse per l’analisi dei dati mediante SQL e OLAP. Introduzione alle tecniche di data mining e machine learning (classificazione, clustering, regole di associazione) applicate al processo di data science.'),
 (5,'Architetture dei Sistemi di Elaborazione',30,'2025-01-23','Corso incentrato sull’architettura dei sistemi basati su microprocessore. Approfondisce le architetture CISC, RISC, superscalari, pipelined e ARM, la gerarchia della memoria (cache L1/L2), e i bus di sistema. Include lo sviluppo di firmware in C e assembler, con esercitazioni pratiche su board ARM per la gestione di periferiche (GPIO, timer, UART, ecc.). Fornisce competenze avanzate nella programmazione di sistemi embedded e nel debug a basso livello.'),
 (6,'Tecnologie e Servizi di Rete',27,'2025-01-23','Studio avanzato delle tecnologie e architetture delle reti di calcolatori, con approfondimenti su progettazione di reti IPv4/IPv6, Ethernet e protocolli di routing Internet. Analisi delle VPN (customer e provider-provisioned), del protocollo MPLS, e delle tecniche per la qualità del servizio (QoS) nelle reti IP. Introduzione alle reti ottiche, alle reti cellulari (dal GSM al 5G) e all’analisi e predizione del traffico di rete. Il corso fornisce competenze teoriche per analizzare e ottimizzare reti moderne e servizi Internet avanzati.'),
 (7,'Software Engineering I',30,'2025-09-10','Studio dei principi, metodologie e strumenti per lo sviluppo e la gestione di progetti software complessi. Il corso ha approfondito l’analisi e la formalizzazione dei requisiti, la progettazione con UML, la gestione di progetto (WBS, Gantt, PERT) e le tecniche di testing (white-box, black-box, unit, integration, system). Particolare attenzione è stata dedicata al lavoro di squadra e alle metodologie agili per lo sviluppo collaborativo di sistemi software di grandi dimensioni.'),
 (8,'Applicazioni Web I',28,'2025-07-26','Studio delle principali tecniche per la realizzazione di applicazioni web distribuite, con particolare attenzione alla programmazione front-end tramite JavaScript e il framework React. Il corso ha approfondito i paradigmi di programmazione moderni per lo sviluppo di Single Page Applications (SPA), l’interazione con API REST e la progettazione di architetture client-server. Sono stati trattati inoltre aspetti di sicurezza, robustezza, interoperabilità e prestazioni, fornendo competenze pratiche per la realizzazione completa di applicazioni web moderne.'),
 (9,'Programmazione di Sistema',30,'2025-07-01','Studio dell’architettura e dei principi di progettazione dei sistemi operativi, con approfondimento sui meccanismi interni di gestione delle risorse (processi, memoria, dispositivi, file system) e sull’implementazione di moduli di sistema. La seconda parte ha riguardato la programmazione di sistema e concorrente in ambienti Unix/Linux e Windows, includendo l’uso di system call, la gestione avanzata della memoria, dei file e dei thread, e l’introduzione al linguaggio Rust per lo sviluppo sicuro e concorrente.'),
 (10,'Information Systems',28,'2025-02-20','Studio delle metodologie e tecnologie per la progettazione, gestione e valutazione di sistemi informativi a supporto dei processi aziendali. Il corso ha trattato la modellazione dei processi con UML e BPMN, l’analisi organizzativa, la valutazione di costi, benefici e performance (KPI, CSF, BSC), e le principali classi di sistemi informativi (ERP, CRM, SCM). Sono stati inoltre approfonditi i modelli di riferimento COBIT e ITIL e le tecnologie per la gestione dei workflow, fornendo competenze per analizzare, progettare e ottimizzare processi aziendali e i relativi sistemi di supporto.'),
 (11,'Basi di Dati',28,'2023-06-26','Studio dei sistemi di gestione di basi di dati (DBMS). Il corso approfondisce la progettazione concettuale e logica tramite il modello Entità-Relazione, il modello relazionale, l’algebra relazionale e il linguaggio SQL per la definizione, interrogazione e gestione dei dati. Sono trattati inoltre viste, transazioni, trigger e accesso ai dati da applicazioni client-server. Le attività di laboratorio consentono di acquisire esperienza pratica con strumenti commerciali e open-source per la progettazione e lo sviluppo di applicazioni basate su database.'),
 (12,'Calcolatori Elettronici',26,'2023-06-23','Studio dei concetti fondamentali relativi ai sistemi di elaborazione dell’informazione, con particolare attenzione all’architettura, al funzionamento e alla progettazione dei componenti hardware e software. Il corso approfondisce i sistemi a microprocessore, l’interazione tra processore, memoria e periferiche, e introduce la programmazione in linguaggio Assembly per comprendere il funzionamento a basso livello dei sistemi di calcolo. Sono trattati inoltre i principi dei processori CISC, RISC e superscalari, fornendo una base solida per corsi avanzati come Sistemi Operativi.'),
 (13,'Sistemi Operativi',31,'2024-02-27','Studio dei principi fondamentali dell’architettura dei sistemi operativi e delle tecniche di programmazione di sistema e concorrente. Il corso approfondisce i sistemi UNIX/Linux, includendo l’uso di comandi utente e di amministrazione, shell scripting e system call per la gestione di processi e thread. Vengono trattati temi quali sincronizzazione, comunicazione tra processi, gestione delle risorse e scheduling, con attività di laboratorio pratiche in ambiente Linux per consolidare le competenze apprese.'),
 (15,'Programmazione a Oggetti',28,'2024-07-24','Studio delle tecniche di sviluppo software basate sul paradigma a oggetti attraverso l’uso del linguaggio Java. Il corso affronta i concetti fondamentali della progettazione orientata agli oggetti (classi, ereditarietà, interfacce, polimorfismo) e l’utilizzo delle librerie standard Java (collezioni, stream, gestione I/O, thread). Sono inoltre introdotti i principi di Ingegneria del Software, tra cui ciclo di vita del software, UML, design pattern, testing (JUnit) e gestione della configurazione, con attività pratiche di sviluppo in IDE e uso di sistemi di versionamento.'),
 (16,'Introduzione alle Applicazioni Web',31,'2024-02-09','Studio dei principi fondamentali delle architetture web e dei protocolli di comunicazione alla base del funzionamento delle applicazioni online. Il corso approfondisce l’uso delle tecnologie web principali – HTML5, CSS3 e JavaScript – per la realizzazione di interfacce moderne, accessibili e responsive. Viene inoltre introdotto il framework Flask (Python) per lo sviluppo del backend, comprendendo la gestione di database, sessioni e autenticazione. Attraverso attività pratiche, gli studenti imparano a progettare e sviluppare un’applicazione web completa di media complessità, curando sia l’aspetto tecnico che visivo secondo i principi del web design moderno.');
INSERT INTO "Features" ("id","id_exam","name") VALUES (5,4,'DBMS'),
 (6,4,'Data Warehouse'),
 (7,4,'NoSQL'),
 (8,4,'OLAP'),
 (9,5,'C'),
 (10,5,'Assembler'),
 (11,5,'ARM'),
 (12,5,'LPC1768 programming'),
 (13,6,'IPv4'),
 (14,6,'IPv6'),
 (15,6,'MPLS'),
 (16,6,'VPN'),
 (17,6,'LAN'),
 (18,7,'Testing'),
 (19,7,'JavaScript'),
 (20,7,'TypeORM'),
 (21,7,'SwaggerAPI'),
 (22,8,'React'),
 (23,8,'SQLite'),
 (24,8,'Express'),
 (25,7,'REST'),
 (26,9,'Rust'),
 (27,9,'OS internals'),
 (28,9,'React'),
 (29,9,'API programming'),
 (30,10,'KPI'),
 (31,10,'CSM'),
 (32,10,'Business models'),
 (33,11,'DBMS'),
 (34,11,'SQLite'),
 (35,11,'UML'),
 (36,11,'E-R Models'),
 (37,12,'Assembler'),
 (38,12,'OS'),
 (39,13,'OS'),
 (40,13,'Bash'),
 (41,13,'Linux'),
 (45,15,'Java'),
 (46,15,'JUnit'),
 (47,15,'UML'),
 (48,16,'HTML'),
 (49,16,'CSS'),
 (50,16,'Flask'),
 (51,16,'JavaScript');
COMMIT;
